
  List data = [
    {
      "id": "L-1001",
      "Brand": "lenovo",
      "Description": "Laptop",
      "PurchasedDate": "01/01/2020",
      "Category": "HP",
      "Model": "thinkbook g4",
      "SerialNumber": "MP24C06F",
      "Cost": "8000.0",
      "AssignedTo": "NA",
      "LastScanDate": "03/20/2024",
      "DueDate": "NA",
      "DisposedDate": "NA",
      "CreatedDate": "03/20/2024",
      "Site": "Lahore Office",
      "Location": "HAFIZ CENTER",
      "Depreciation": "Yes",
      "DepreciationMethod": "Sum of the Years Digits",
      "TotalCost": "99",
      "AssetLife": "66",
      "SalvageValue": "99",
      "DateAcquired": "04/16/2024",
          "img":'na'

    },
    {
      "id": "AH-01",
      "Brand": "dell",
      "Description": "RFID",
      "PurchasedDate": "01/04/2024",
      "Category": "Electronics",
      "Model": "0001F4",
      "SerialNumber": "MP24C06F",
      "Cost": "8000.0",
      "AssignedTo": "NA",
      "LastScanDate": "03/20/2024",
      "DueDate": "NA",
      "DisposedDate": "NA",
      "CreatedDate": "03/20/2024",
      "Site": "Lahore Office",
      "Location": "Islamabad",
      "Depreciation": "Yes",
      "DepreciationMethod": "Sum of the Years Digits",
      "TotalCost": "99",
      "AssetLife": "66",
      "SalvageValue": "99",
      "DateAcquired": "04/16/2024",
          "img":'na'

    },
    {
      // "id": "5415211983601",
      "id": "541521",
      "Brand": "lenovo",
      "Description": "IPHONE",
      "PurchasedDate": "01/01/2020",
      "Category": "NA",
      "Model": "PRO",
      "SerialNumber": "MP24C06F",
      "Cost": "8000.0",
      "AssignedTo": "NA",
      "LastScanDate": "03/20/2024",
      "DueDate": "NA",
      "DisposedDate": "NA",
      "CreatedDate": "03/20/2024",
      "Site": "Lahore Office",
      "Location": "Faislabad",
      "Depreciation": "Yes",
      "DepreciationMethod": "Sum of the Years Digits",
      "TotalCost": "99",
      "AssetLife": "66",
      "SalvageValue": "99",
      "DateAcquired": "04/16/2024",
          "img":'na'

    }
  ];

